# Generated by Django 3.2.12 on 2022-03-13 04:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('PENDING', 'Pending'), ('TERMINATED', 'Terminated')], default='TO_DO')),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
